spring.application.name=busproject
spring.datasource.url=jdbc:postgresql://localhost:5432/busproject
spring.datasource.username=postgres
spring.datasource.password=gadaaa21
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.web=DEBUG